### ISSUE TITLE
Use in a web worker

### ISSUE THREAD

**Issue by dancerphil** [wooorm/parse-entities#16]
I'm using `web worker` to highlight code, but in some case, refractor tried to use document and failed since we do not have `document` in `web worker`.

It is quite difficult to reproduce this bug because it only happens to a huge file and I don't know which line cause this problem.

I think the error may help:

```
in ReferenceError: document is not defined
    at decodeEntity (decode-entity.browser.js:15)
    // node_modules/parse-entities/decode-entity.browser.js

    at parse (index.js:251)
    // node_modules/parse-entities/index.js

    at parseEntities (index.js:110)
    // node_modules/parse-entities/index.js

    at attributes (core.js:214)
    // node_modules/refractor/core.js

    at Function.stringify (core.js:176)
    // node_modules/refractor/core.js

    at stringifyAll (core.js:200)
    // node_modules/refractor/core.js

    at Function.stringify (core.js:155)
    // node_modules/refractor/core.js

    at Refractor.highlight (prism-core.js:277)
    // node_modules/prismjs/components/prism-core.js

    at Refractor.highlight (core.js:119)
    // node_modules/refractor/core.js

    at highlightText (index.js:7)
    // my own code
```

It will be grateful if you know why and how to fix it.

If not, I could help find some reproduce.

**Comment by wooorm** [comment]
Hi there, welcome!

If you are in a web worker, you can’t use `document`, indeed.
We support [browsers and non-browsers](https://github.com/wooorm/parse-entities/blob/d120e6b7199364ccfa3c0081d1d6c32e23678205/package.json#L20-L30).
Your bundler (such as Webpack / Rollup / Browserify) picks up on this (by default it’ll pick the browser version).
If you are planning to bundle something for a web worker, you should tell your bundler to *not* pickup the browser version.
How to do that, depends on your bundler, for webpack, it’s [described here](https://webpack.js.org/configuration/target/) I think.
