### ISSUE TITLE
[null] Numeric character references must be terminated by a semicolon (alex)

### ISSUE THREAD

**Issue by sdwheeler** [wooorm/parse-entities#22]
I am using Alex with the textlint extension in VS Code. I am getting the following error message:

> [null] Numeric character references must be terminated by a semicolon (alex)

Consider the following markdown:

```markdown
- A &#x2705; indicates that the version of the OS or PowerShell is still supported
- A &#x274c; indicates that the version of the OS or PowerShell isn't supported
- A &#x1f7e1; indicates the version of PowerShell is no longer supported on that version of the OS
- When both the version of the OS and the version of PowerShell have &#x2705;, that combination is
  supported

|    Alpine     | 7.0 (LTS) |    7.1    | 7.2 (LTS-current) | 7.3 (preview) |
| ------------- | :-------: | :-------: | :---------------: | :-----------: |
| &#x2705; 3.14 | &#x274c;  | &#x274c;  |     &#x2705;      |   &#x2705;    |
| &#x2705; 3.13 | &#x274c;  | &#x1f7e1; |     &#x2705;      |   &#x2705;    |
| &#x2705; 3.12 | &#x2705;  | &#x1f7e1; |     &#x2705;      |   &#x2705;    |
| &#x2705; 3.11 | &#x274c;  | &#x1f7e1; |     &#x274c;      |   &#x274c;    |
| &#x274c; 3.10 | &#x1f7e1; | &#x1f7e1; |     &#x274c;      |   &#x274c;    |
| &#x274c; 3.9  | &#x1f7e1; | &#x1f7e1; |     &#x274c;      |   &#x274c;    |
```

The error is being flagged for all the numeric character references in column 2-5 in the markdown table above. It is not flagging any of the numeric character references in column 1 or in the list items above. If I add any non-space or non-pipe (`|`) character after the numeric character reference, the error goes away.

Here is a screenshot of the errors in the editor so you can see the line and column references.

![image](https://user-images.githubusercontent.com/19415881/170532076-fe7875af-4ad0-45f1-9191-d0397c51e2ed.png)

**Comment by wooorm** [comment]
I think that error is no longer surfaced for a while now. Can you update alex?

**Comment by wooorm** [comment]
Also rather weird that it's even warned about. Can you paste the markdown?

**Comment by sdwheeler** [comment]
The markdown is in my opening comment.

**Comment by sdwheeler** [comment]
I am using the `textlint-rule-alex@3.0.0` rule package with textlint. That is the latest version of that package. It is pinned to use alex 9.1.1. 

```json
  "dependencies": {
    "alex": "^9.1.1",
    "textlint-rule-helper": "^2.2.1"
  }
```

**Comment by sdwheeler** [comment]
Is there a way to configure Alex to suppress rules I don't want to use, like  this `parse-entities` rule?

**Comment by wooorm** [comment]
Hmm. It might be easiest to get `textlint` folks to update `alex` in their rule, or use alex directly. I don’t know why this issue is happening in some cases, but it’s an intermediate problem in `remark-parse`, not with this project, and `remark-parse` has solved this 2 years ago already!

Edit: It could also be a problem with `textlint` btw, that they pass incorrect text when in tables? I haven’t hear of this in alex or remark itself

**Comment by wooorm** [comment]
Closing, this hasn’t been an error for ages in `alex` itself. I defer to intermediate packages.
