### ISSUE TITLE
Remove unused character-entities dependency

### ISSUE THREAD

**Issue by alexparish** [wooorm/parse-entities#24]
It seems the `character-entities` dependency is no longer used. Can it be removed?

Happy to raise a PR for this.

**Comment by wooorm** [comment]
Hi! I Would love a PR, thanks! It was moved to `decode-named-character-reference` it seems.

**Comment by alexparish** [comment]
Great! It's a tiny PR: https://github.com/wooorm/parse-entities/pull/25

**Comment by wooorm** [comment]
Thanks, released in [`4.0.2`](https://github.com/wooorm/parse-entities/releases/tag/4.0.2)!
